AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

###############################################################################
# GLOBALS
###############################################################################
Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Layers:
      - arn:aws:lambda:us-east-1:195275634967:layer:common-utils-py312:8
    Environment:
      Variables:
        JWT_ALGORITHM: "HS256"
        MONGODB_DB_NAME: "crm"
        MONGODB_URI: "mongodb+srv://crm:sCEVRRjfDzUi8Ve7@crm.oeswogj.mongodb.net/crm?retryWrites=true&w=majority&tls=true"

###############################################################################
# API HTTP
###############################################################################
Resources:

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: [GET, POST, PUT, DELETE, OPTIONS]
        AllowHeaders: [Content-Type, Authorization]

  #############################################################################
  # FUNCIÓN PRINCIPAL (APP)
  #############################################################################
  ModuleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Events:
        GetModules:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /modules
            Method: GET
        GetModulesById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /modules/{id}
            Method: GET
        CreateModule:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /modules
            Method: POST
        UpdateModule:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /modules/{id}
            Method: PUT
        DeleteModule:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /modules/{id}
            Method: DELETE
        PublicCreateModule:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /modules/public
            Method: POST
        # onboarding
        Onboarding:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /onboarding
            Method: POST

Outputs:
  ApiBaseUrl:
    Description: "Base URL de la API (stage Prod)"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
